language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install flake8
  - pip install Django==$DJANGO
  - pip install django-jsonfield==0.8.12
  - pip install mock
  - pip install django-nose
  - pip install requests
  - pip install .
script:
  - flake8 .
  - python runtests.py
