language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO
  - pip install -q django-jsonfield==0.8.12
  - pip install -q mock
  - pip install -q django-nose
  - pip install -q requests
  - pip install -q pylint
  - pip install -q pinax.checkers
  - pip install -e .
before_script:
  - "pylint --rcfile=.pylintrc coinbase"
script:
  - python runtests.py
